### ISSUE TITLE
can you help to change product Description to textarea? 

### ISSUE THREAD

**Issue by epubreader** [lawandothman/shopcart#96]
Thanks for your program,
can you help to change product Description to textarea in product edit page? 
 add a editor to field product description and can upload image in this editor?

**Comment by lawandothman** [comment]
Hi, 

Thanks for opening the issue. 

This feature already exists if you are logged in as an admin. You can view the products and edit their details (including changing the description and uploading a new image) 


![Screenshot 2021-05-08 at 22 17 59](https://user-images.githubusercontent.com/58405138/117553773-5b8dfd80-b04b-11eb-9d99-4e4198f3948f.png)
